### PR TITLE
Refactoring based on code smell analysis

### PR DESCRIPTION
**Pull request by MithunKhanna**
_Following changes were made after running Come smell detection tool and analysing the for code quality_</br>

Tool used: [DesigniteJava](https://www.designite-tools.com/products-dj) </br>
*Changes*
* Decomposed complex conditional in createPropertySet method by introducing explaining variables
* Renamed variables in decodeLines method for better readability
* Extracted a method to check for illegal characters and is extendable to any number of inputs
* checkNode method of Composer package is more interested in methods from Parser package and does not call any method from composer. Moved checkNode to Parser for better cohesion
* Cyclic dependency was present between Emitter and DumperOptions Class. DumperOptions depends on global constants from Emitter. Converted bidirectional association to unidirectional association by introducing the constants to DumperOptions class
* Base64Coder performs both encoding and decoding in base64 format breaking single responsibility principle. Extracted class Base64Encoder to handle all operations related to encoding.

### CODE REVIEW

**Comment by asomov** [comment]
Thank you for the contribution.
Since the github is often oudated, can you please merge the latest commits from master ? (bitbucket is the source, github is the mirror)
Please do not modify sources in external package. It contain sources from other places with specific licenses.I was already contacted in the past and I do not want waste time again. Please keep them as they are (or contact the initial owners for any changes)
Moving method checkNode caused code duplication. What is the added value ? I am afraid it is backwards incompatible for those who use low level API (to parse/dump comments for instance)

**Comment by MithunKhanna** [comment]
Thank you for your comments. I will merge latest changes from master. <br>
I will revert the changes in external package. <br>
Refactoring was done from a code quality perspective. Code smell - Feature Envy was detected in  checkNode as it depended more on methods from parser than it's own class. It is moved for better cohesion of classes. <br>
If it is not backward compatible, I will revert the changes. <br>

**Comment by asomov** [comment]
Base64Coder is not the same as it was. Base64Encoder is present but not used.
I recommend you to be more accurate in the contribution. You may drop the whole branch and re-create only the changes which are required. 
Being backwards compatible is important. SnakeYAML just released version 2 with major consequences - I do not want to disturb the community again.

**Comment by asomov** [comment]
I do not see that the latest commits are merged into your code.

**Comment by asomov** [comment]
@MithunKhanna can you please have a look ?
https://bitbucket.org/snakeyaml/snakeyaml/pull-requests/73

**Comment by MithunKhanna** [comment]
Hi @asomov, 
Thank You for your time and consideration of my work. </br>
I have looked into the above request and changes look good to me. </br>

Apart from the external package,  While looking through the repository I am finding that the written tests do not follow a consistent pattern. Some are written in JUnit3 pattern and others in JUnit5 making it difficult to maintain. </br>
Note - I was analyzing and refactoring on the repository as part of my course work in university

**Comment by asomov** [comment]
SnakeYAML was created far before JUnit 5

**Comment by asomov** [comment]
@MithunKhanna may I ask you to look into [SnakeYAML Engine ](https://bitbucket.org/snakeyaml/snakeyaml-engine/src/master/)? I wish to switch slowly to it

**Comment by asomov** [comment]
@MithunKhanna can you please try to implement useful feature in SnakeYAML ? It gives a real value to the community.
This is the feature:
https://bitbucket.org/snakeyaml/snakeyaml/issues/1084/dump-as-json

I will help you to implement it !

**Comment by MithunKhanna** [comment]
Hi @asomov 
Thank you for your consideration. I am looking into SnakeYAML Engine and I will look into dump as json feature.

Thanks,
Mithun B

**Comment by asomov** [comment]
@MithunKhanna any progress ?

**Comment by MithunKhanna** [comment]
Hi @asomov,
I should have some progress by this weekend.

Thanks for your patience and consideration

**Comment by asomov** [comment]
@MithunKhanna which progress ? What are you busy with ?

**Pull request closed without merging**
