### PR TITLE
Update module-info.java

### PR DESCRIPTION
**Pull request by rimago**
add exports org.yaml.snakeyaml.inspector

### CODE REVIEW

**Comment by asomov** [comment]
SnakeYAML keeps Java 7/8 compatibility. It is important. Some libraries are not yet on Java 11

**Comment by rimago** [comment]
Ok, but is it still possible to build it with java 7? I was not able to do so, because some dependencies were build with newer Java versions

**Comment by asomov** [comment]
Which dependency is on Java 11 ? Java 11 is used merely to support modules

**Comment by Maran23** [comment]
> Which dependency is on Java 11 ? Java 11 is used merely to support modules

Right now, snakeyaml does not work when used inside your own `module.info` because `org.yaml.snakeyaml.inspector;` is missing.

**Comment by asomov** [comment]
`org.yaml.snakeyaml.inspector` has been removed already in the latest release

**Comment by Maran23** [comment]
Can be closed, now fixed by https://github.com/snakeyaml/snakeyaml/pull/8

**Pull request closed without merging**
