### PR TITLE
feat(comment): Add an annotation to set comments in serialized output

### PR DESCRIPTION
**Pull request by Kricket**

### CODE REVIEW

**Comment by Kricket** [comment]
Hello,

I created this PR because I work on a project where we use SnakeYML to serialize POJOs with lots of data that is then modified by hand by our users.

The goal is to be able to declare that a comment should be added to a YML key by using the Comment annotation.

I'm not really familiar with the source code or goals of the project, so if I'm missing something (which seems likely...), don't hesitate to let me know what needs to be changed.

**Comment by maslovalex** [comment]
Hi @Kricket.

Thank you for your interest in SnakeYaml. I see how this could be useful for some use cases.

But here is one thing I don't like about this: SnakeYaml specific Annotation.
I don't like when domain model depends on the parser library. 
One solution would be to introduce as snakeyaml-annotation module containing only annotations and no dependencies to parser itself. But I do not think this is going to happen in near future.

I think it is better to give a possibility to, let's say, post-process/modify nodes at the stage of representing, so anybody can add their functionality to extend default one.

**Comment by Kricket** [comment]
Hello,

OK, that's fine. But as I'm not really familiar with the code...could you explain the different modules and how they're interrelated?

The problem with post-processing (if I understand your suggestion) is that it makes it much more complicated to achieve the desired functionality: instead of just tacking on an annotation, the user would have to write some sort of extension, have a way of figuring out which Node corresponds to the object needing a comment...basically, they would have to get into the internals of SnakeYaml for what is essentially a decoration in the output.

**Comment by nimelord** [comment]
Sorry for off top, but I have no choice, because of permissions.
Here (in github) issues tab is absent, and in https://bitbucket.org/snakeyaml/snakeyaml/ create button is disabled:
image

So, how can I create bug report?

**Comment by asomov** [comment]
this is the mirror. Go to the origin

**Comment by nimelord** [comment]
> this is the mirror. Go to the origin

Ok. reported: https://bitbucket.org/snakeyaml/snakeyaml/issues/1088/error-when-trying-to-load-an-object-with

**Pull request closed without merging**
