### PR TITLE
Add parameter free constructor, fix upgrade jar version startup failure

### PR DESCRIPTION
**Pull request by diaodiaofly**
Upgrading snakeyaml from version 1. x to 2.2 will fail,
The classes in the snakeyaml project need to add non parametric constructs

### CODE REVIEW

**Comment by asomov** [comment]
A lot of deprecated methods were removed in version 2.0
Feel free to change your code to use the proper constructor.
(there are many other methods which were removed - do you suggest to restore them all?)

**Comment by diaodiaofly** [comment]
> A lot of deprecated methods were removed in version 2.0 Feel free to change your code to use the proper constructor. (there are many other methods which were removed - do you suggest to restore them all?)

 i think we can add this parameter free construct to help users solve the problem of Spring Boot startup error when upgrading

**Comment by asomov** [comment]
The best way to help is to change your code to get rid of the old stuff.
How is it connected to Spring Boot?
The Spring community is using the new code more than a year.

**Comment by diaodiaofly** [comment]
> The best way to help is to change your code to get rid of the old stuff. How is it connected to Spring Boot? The Spring community is using the new code more than a year.

Upgrading snakeyaml separately in springboot 2.5.15 version may result in project startup errors, as the Representation does not have a constructor method
QQ20240825-102916

**Comment by asomov** [comment]
this is not related to SnakeYAML. When you wish to keep an old version of Spring Boot - keep its dependencies.
To use the recent SnakeYAML version - migrate to recent Spring Boot.
For your information - there is no problem with CVE in the version you have. Keep using it.

**Comment by asomov** [comment]
@diaodiaofly have you found a solution?

**Comment by diaodiaofly** [comment]
> @diaodiaofly have you found a solution?

Not at the moment, I think you should consider using Spring Boot for low-level users

**Comment by asomov** [comment]
@diaodiaofly your message is unclear.
We do use Spring Boot. They do have all the necessary things to function properly. The whole community goes further.
If you have the exact proposal - feel free to contribute.

**Comment by asomov** [comment]
please upgrade to Spring Boot 3
https://spring.io/blog/2023/11/23/spring-boot-2-7-18-available-now#end-of-open-source-support-for-spring-boot-2x

**Pull request closed without merging**
